### PR TITLE
Add lon1.box.populi.ml to games JSON

### PR DESCRIPTION
**Pull request by tornadomasterrace**

### CODE REVIEW

**Comment by tornadomasterrace** [comment]
This is an Oracle Cloud free ARM VM in London, good ping from UK at least

**Comment by tornadomasterrace** [comment]
This is the experiment it's running: https://old.reddit.com/r/airmash/comments/ug6b6c/colliding_boxes_v2/

(but now I can build ab-server with swc in 300ms, probably there will be more ;) )

**Comment by wight-airmash** [comment]
Cross-server user stats sync disabled here, right?

**Comment by tornadomasterrace** [comment]
Stats sync is disabled here

**Comment by tornadomasterrace** [comment]
Any idea why it's not showing up? It looks like one of https://github.com/airmash-refugees/airmash-services needs restarted, but can't see anything in the org for it

https://github.com/airmash-refugees/airmash-services/blob/master/servers/games.js has some strange magic for test vs non-test, but I can't seem to make it return the new server using any Origin:/Referer: header

**Comment by wight-airmash** [comment]
@congratulatio we need help, the list of game servers is not updated after merge.

**Comment by congratulatio** [comment]
@tornadomasterrace @wight-airmash sorry for the delay, I didn't have it set up to auto-download updated games.txt from this repo - fixed now. New server looks good, neat idea with the boxes :slightly_smiling_face:

**Pull request merged**
