### PR TITLE
preparing for shutdown of us ffa2

### PR DESCRIPTION
**Pull request by robertcope**
I am preparing to shut down the us ffa2 server at airmash.trackjunkies.org. We just never got much traction there, unfortunately.

### CODE REVIEW

**Comment by congratulatio** [comment]
That is indeed unfortunate - thank you for hosting for these last few months though!

When you do the final shutdown, would you mind sending me your `data/user-stats.json` file? Then I can integrate the stats with the other ab-server at `eu-ffa1`.

**Review by congratulatio — APPROVED** [review]

**Comment by robertcope** [comment]
No problem, I was really hoping that a more modern server in the USA would
help build a community there, but it just never happened.

The user-stats.json file should be attached.

robert

**Comment by congratulatio** [comment]
Agreed, it is a shame, it did seem a promising idea.

I think GitHub stripped out your attachement - would you mind sending to airmashonline@gmail.com instead?

**Comment by wight-airmash** [comment]
I remember that about 3 months ago (early v6 alpha) I saw online about 50 players and it was cool. I hope the decision was not based on summer months statistics, because in summer time (school holidays) the interest in the game was always lower than usual, even in 2018. Anyway, thank you for the hosting!

**Pull request merged**
