### PR TITLE
Add new US server, ffa2

### PR DESCRIPTION
**Pull request by robertcope**
This will add a new user server, ffa2 @ airmash.trackjunkies.org/ffa1 to the list

### CODE REVIEW

**Comment by congratulatio** [comment]
Thanks for contributing a new server to the game!

Could you confirm this is the correct endpoint? I'm seeing a 502 error when testing:

```
curl -D - https://airmash.trackjunkies.org/ffa1
HTTP/2 502 
date: Sun, 15 Mar 2020 19:51:08 GMT
content-type: text/html
set-cookie: __cfduid=d834fbada40792c3cbde744198effd3211584301867; expires=Tue, 14-Apr-20 19:51:07 GMT; path=/; domain=.trackjunkies.org; HttpOnly; SameSite=Lax; Secure
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
strict-transport-security: max-age=15552000; includeSubDomains; preload
x-content-type-options: nosniff
server: cloudflare
cf-ray: 5748c4723db9ce3b-LHR
alt-svc: h3-27=":443"; ma=86400, h3-25=":443"; ma=86400, h3-24=":443"; ma=86400, h3-23=":443"; ma=86400

<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.16.1 (Ubuntu)</center>
</body>
</html>
```

**Comment by robertcope** [comment]
Hum, interesting. It seems like WebSockets are working but https requests aren't, ie you can play the game at https://airmash.trackjunkies.org/ and it's connected to the airmash.trackjunkies.org/ffa1 backend. Being honest, this is my first time playing with WebSockets, so I'm sure it's an error in my nginx proxy setup.

**Comment by congratulatio** [comment]
I see what you mean, after also adding your server to https://test.airmash.online, I can connect and play just fine. But the player count, served over the non-WebSocket endpoint, isn't displayed.

If it helps to compare, here's the nginx config for eu.airmash.online: https://gist.github.com/congratulatio/147ad86d2e9a0ecb8c3f7838e199a1df

**Comment by robertcope** [comment]
Okay, I think it is setup correctly now.

**Comment by congratulatio** [comment]
Looks great, I've merged your change, and also renamed the existing US FFA server to be US FFA #[]()1. Thanks!

**Pull request merged**
